[package]
name = "kalk_cli"
version = "0.2.0"
authors = ["PaddiM8"]
edition = "2018"
readme = "../README.md"
description = "A calculator that supports user-defined functions, variables and units, and can handle fairly ambiguous syntax."
repository = "https://github.com/PaddiM8/kalk"
license = "MIT"
keywords = ["math", "calculator", "cli", "command-line"]
categories = ["mathematics", "command-line-utilities"]

[[bin]]
path = "src/main.rs"
name = "kalk"

[dependencies]
kalk = { path = "../kalk", version = "^0.2.0" }
rustyline = "6.1.2"
ansi_term = "0.12"
regex = "1"
phf = { version = "0.8", features = ["macros"] }
