[package]
name = "kalk"
version = "0.1.0"
authors = ["paddi"]
edition = "2018"

[profile.release]
panic = "abort"
#lto = true
#codegen-units = 1
#incremental = false

[dependencies]
phf = { version = "0.8", features = ["macros"] }
rug = "1.9.0"
test-case = "1.0.0"
regex = "1"
