[package]
name = "kalk"
version = "0.1.4"
authors = ["PaddiM8"]
edition = "2018"
readme = "README.md"
description = "A math evaluator library that supports user-defined functions and variables and can handle fairly ambiguous syntax."
repository = "https://github.com/PaddiM8/kalk/tree/master/kalk"
license = "MIT"
keywords = ["math", "calculator", "evaluator"]
categories = ["mathematics", "parser-implementations"]

[profile.release]
panic = "abort"
#lto = true
#codegen-units = 1
#incremental = false

[dependencies]
phf = { version = "0.8", features = ["macros"] }
rug = "1.9.0"
test-case = "1.0.0"
regex = "1"
