name: Publish

on:
  push:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1.0.1
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish crate
      run: cargo publish --manifest-path kalk/Cargo.toml --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
    - name: Publish CLI
      run: cargo publish --manifest-path kalk_cli/Cargo.toml --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose
      
  release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.target }}
    strategy:
      matrix:
        target: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses:  PaddiM8/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTRA_FILES: "README.md LICENSE"
